.Dd March 18, 2020
.Dt FLUTTER_DARTRIX
.Sh NAME
.Nm app
.Nd Dartrix template for generating a simple Flutter application.
.Sh SYNOPSIS
.Nm dartrix:new flutter -t app
.Op Fl pdagh
.Sh DESCRIPTION
.Pp
package:flutter_dartrix contains templates for generating Flutter code.
To list them use the dartrix:list command.
.Pp
The following template parameters are available:
.Bl -tag -width indent
.It Fl p, -project
Project name. Default: flapp
.It Fl d, -domain
Domain in dotted syntax, e.g. foo.bar.com. Default: example.org
.It Fl a, -app
Application name. Default: flapp
.It Fl g, -greeting
A greeting, such as 'Hello'. Default: 'Hello'
.It Fl h, -help
Help
.El
.Sh EXAMPLES
Example goes here...
