.Dd March 18, 2020
.Dt FLUTTER_DARTRIX
.Sh NAME
.Nm flutter_dartrix
.Nd Dartrix template library for generating Flutter code
.Sh SYNOPSIS
dartrix:new flutter -t <template>
.Sh DESCRIPTION
.Pp
package:flutter_dartrix contains templates for generating Flutter code.
To list them use the dartrix:list command.
.Sh EXAMPLES
Example goes here...
