name: flutter_dartrix
description: Dartrix template plugin package.  Contains templates for Flutter code - apps, packages, plugins, widgets, etc.
homepage: https://github.com/mobileink/flutter_dartrix
version: 0.1.0

dependencies:
  args: ^1.5.3

dartrix:
  version: 0.1.18-alpha

environment:
  sdk: '>=2.6.0 <3.0.0'

