name: flutter_dartrix
docstring: Templates for Flutter programs, libraries, etc.
description: Dartrix template plugin package.  Contains templates for Flutter code - apps, packages, plugins, widgets, etc.
homepage: https://github.com/mobileink/flutter_dartrix
version: 0.2.3

dependencies:
  args: ^1.5.3

dartrix:
  version: 0.2.0

environment:
  sdk: '>=2.6.0 <3.0.0'

